import 'adventurer_template.dart';

// PLACEHOLDER NOTE: Stats marked with * are confirmed from the rulebook.
// All others are placeholders to be corrected from the physical boards.
const List<AdventurerTemplate> kAllTemplates = [
  AdventurerTemplate(
    id: 'beren',
    name: 'Beren',
    species: 'Human',
    healthStart: 3,
    healthPotential: 5,
    magicStart: 3,
    magicPotential: 7,
    skillStart: 1,
    skillPotential: 3,
    actionStart: 2,
    actionPotential: 2,
    rankXpCosts: [6, 5, 3, 3, 3],
    guilderCost: 71,
    startingXp: 4,
  ),
  AdventurerTemplate(
    id: 'greet',
    name: 'Greet',
    species: 'Grobbler',
    healthStart: 3,
    healthPotential: 4,
    magicStart: 1,
    magicPotential: 4,
    skillStart: 2,
    skillPotential: 5,
    actionStart: 2,
    actionPotential: 3,
    rankXpCosts: [5, 5, 4, 3, 2],
    guilderCost: 75,
    startingXp: 2,
  ),
  AdventurerTemplate(
    id: 'grogmar',
    name: 'Grogmar',
    species: 'Ormen',
    healthStart: 5,
    healthPotential: 7,
    magicStart: 1,
    magicPotential: 3,
    skillStart: 1,
    skillPotential: 3,
    actionStart: 2,
    actionPotential: 2,
    rankXpCosts: [4, 4, 4, 3],
    guilderCost: 73,
    startingXp: 2,
  ),
  AdventurerTemplate(
    id: 'moranna',
    name: 'Moranna',
    species: 'Human',
    healthStart: 3,
    healthPotential: 4,
    magicStart: 2,
    magicPotential: 7,
    skillStart: 2,
    skillPotential: 4,
    actionStart: 2,
    actionPotential: 3,
    rankXpCosts: [6, 5, 4, 3, 3],
    guilderCost: 80,
    startingXp: 2,
  ),
  AdventurerTemplate(
    id: 'nerinda',
    name: 'Nerinda',
    species: 'Human',
    healthStart: 4,
    healthPotential: 6,
    magicStart: 1,
    magicPotential: 3,
    skillStart: 2,
    skillPotential: 6,
    actionStart: 2,
    actionPotential: 3,
    rankXpCosts: [5, 4, 3, 3, 2],
    guilderCost: 80,
    startingXp: 3,
  ),
  AdventurerTemplate(
    id: 'syrio',
    name: 'Syrio',
    species: 'Eld',
    healthStart: 4,
    healthPotential: 6,
    magicStart: 1,
    magicPotential: 4,
    skillStart: 1,
    skillPotential: 4,
    actionStart: 2,
    actionPotential: 2,
    rankXpCosts: [5, 4, 4, 3],
    guilderCost: 64,
    startingXp: 3,
  ),
  AdventurerTemplate(
    id: 'callan',
    name: 'Callan',
    species: 'Human',
    healthStart: 4,
    healthPotential: 5,
    magicStart: 1,
    magicPotential: 3,
    skillStart: 1,
    skillPotential: 4,
    actionStart: 2,
    actionPotential: 2,
    rankXpCosts: [4, 3, 4, 2],
    guilderCost: 54,
    startingXp: 1,
  ),
];
