import 'dart:math';

import 'enums.dart';
import 'equipment_item.dart';

class CatalogItem {
  final String id;
  final String name;
  final String category;
  final ItemColor color;
  final Rarity rarity;
  final int rank; // 0 = exclusive / no rank
  final String description;

  const CatalogItem({
    required this.id,
    required this.name,
    required this.category,
    required this.color,
    required this.rarity,
    required this.rank,
    required this.description,
  });

  EquipmentItem toEquipmentItem() {
    final rand = Random();
    final genId =
        List.generate(8, (_) => rand.nextInt(16).toRadixString(16)).join();
    return EquipmentItem(
      id: genId,
      name: name,
      color: color,
      rarity: rarity,
      slots: 1,
      isInnate: false,
    );
  }
}

const List<String> kEquipmentCategories = [
  'Ammo',
  'Armour',
  'Companion Totems',
  'Crafting Materials',
  'Potions',
  'Restoratives',
  'Shield',
  'Weapons - Melee',
  'Weapons - Ranged',
  'Other',
];

const List<CatalogItem> kEquipmentCatalog = [
  // ─── Weapons - Melee ───────────────────────────────────────────────────────
  CatalogItem(id: 'm_dagger', name: 'Dagger', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.common, rank: 1, description: 'Combat 1'),
  CatalogItem(id: 'm_club', name: 'Club', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.common, rank: 1, description: 'Combat 1, Burst'),
  CatalogItem(id: 'm_pick', name: 'Pick', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.common, rank: 1, description: 'Combat 1, Burst, Bludgeoning, Cumbersome'),
  CatalogItem(id: 'm_poison_dagger', name: 'Poison Dagger', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.common, rank: 1, description: 'Combat 1, Poison'),
  CatalogItem(id: 'm_dirk', name: 'Dirk', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.common, rank: 1, description: 'Combat 1, Quickstrike'),
  CatalogItem(id: 'm_throwing_dagger', name: 'Throwing Dagger', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.common, rank: 1, description: 'Combat 1, Balanced'),
  CatalogItem(id: 'm_buckler', name: 'Buckler', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.common, rank: 1, description: 'Combat 1, Parry'),
  CatalogItem(id: 'm_throwing_axe', name: 'Throwing Axe', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.common, rank: 1, description: 'Combat 1, Burst, Balanced'),
  CatalogItem(id: 'm_hammer', name: 'Hammer', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.common, rank: 1, description: 'Combat 1, Burst, Bludgeoning'),
  CatalogItem(id: 'm_trekking_pole', name: 'Trekking Pole', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.common, rank: 1, description: 'Combat 1, Burst, Re-roll Rough Ground'),
  CatalogItem(id: 'm_hatchet', name: 'Hatchet', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.common, rank: 1, description: 'Combat 1, Sharp'),
  CatalogItem(id: 'm_short_sword', name: 'Short Sword', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.common, rank: 1, description: 'Combat 1, Burst, Parry'),
  CatalogItem(id: 'm_shovel', name: 'Shovel', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.common, rank: 1, description: 'Combat 2, Bludgeoning, Cumbersome'),
  CatalogItem(id: 'm_boathook', name: 'Boathook', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.common, rank: 1, description: 'Combat 2, Entangling, Reach 1'),
  CatalogItem(id: 'm_quarterstaff', name: 'Quarterstaff', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 1, description: 'Combat 2, Reach 1'),
  CatalogItem(id: 'm_javelin', name: 'Javelin', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.common, rank: 1, description: 'Combat 2, Quickstrike, Balanced'),
  CatalogItem(id: 'm_axe', name: 'Axe', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.common, rank: 1, description: 'Combat 2, Burst, Sharp'),
  CatalogItem(id: 'm_halberd', name: 'Halberd', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 1, description: 'Combat 2, Burst, Sharp, Reach 1, Cumbersome'),
  CatalogItem(id: 'm_spear', name: 'Spear', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.common, rank: 1, description: 'Combat 2, Reach 1, Sharp'),
  CatalogItem(id: 'm_net', name: 'Net', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 2, description: 'Combat 1, Burst, Entangling, Disarm 2'),
  CatalogItem(id: 'm_mace', name: 'Mace', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 2, description: 'Combat 2, Burst, Bludgeoning'),
  CatalogItem(id: 'm_sword', name: 'Sword', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.common, rank: 2, description: 'Combat 2, Burst, Parry'),
  CatalogItem(id: 'm_long_sword', name: 'Long Sword', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 2, description: 'Combat 2, Burst, Parry, Sharp'),
  CatalogItem(id: 'm_sabre', name: 'Sabre', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 2, description: 'Combat 2, Burst, Sharp'),
  CatalogItem(id: 'm_chakri', name: 'Chakri', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 2, description: 'Combat 1, Sharp, Balanced'),
  CatalogItem(id: 'm_rapier', name: 'Rapier', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 2, description: 'Combat 2, Quickstrike, Sharp'),
  CatalogItem(id: 'm_enchanted_stave', name: 'Enchanted Stave', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 2, description: 'Combat 2, Reach 1, Channel +x Dice'),
  CatalogItem(id: 'm_flail', name: 'Flail', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 2, description: 'Combat 2, Burst, Reach 1, Bludgeoning'),
  CatalogItem(id: 'm_pike', name: 'Pike', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 2, description: 'Combat 2, Sharp, Cumbersome, Reach 3'),
  CatalogItem(id: 'm_machete', name: 'Machete', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 2, description: 'Combat 2, Burst, Sharp, Immunity Entangling'),
  CatalogItem(id: 'm_scythe', name: 'Scythe', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 2, description: 'Combat 3, Burst, Sharp, Cleave, Reach 1, Preparation'),
  CatalogItem(id: 'm_bastard_sword', name: 'Bastard Sword', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 2, description: 'Combat 2, Reach 1, Parry, Sharp'),
  CatalogItem(id: 'm_warhammer', name: 'Warhammer', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 2, description: 'Combat 3, Burst, Cumbersome, Bludgeoning'),
  CatalogItem(id: 'm_trident', name: 'Trident', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 2, description: 'Combat 2, Reach 1, Sharp, Vicious'),
  CatalogItem(id: 'm_whip', name: 'Whip', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 2, description: 'Combat 2, Entangling, Reach 2'),
  CatalogItem(id: 'm_barbed_blade', name: 'Barbed Blade', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 2, description: 'Combat 2, Burst, Vicious, Sharp'),
  CatalogItem(id: 'm_cursed_blade', name: 'Cursed Blade', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 2, description: 'Combat 2, Burst, Reach 1, Sharp, Parry, Curse'),
  CatalogItem(id: 'm_enchanted_gladious', name: 'Enchanted Gladious', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 3, description: 'Combat 1, Burst, Sharp, Channel +x Dice'),
  CatalogItem(id: 'm_heavy_flail', name: 'Heavy Flail', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 3, description: 'Combat 2, Burst, Vicious, Reach 1, Bludgeoning'),
  CatalogItem(id: 'm_enchanted_cudgel', name: 'Enchanted Cudgel', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 3, description: 'Combat 2, Burst, Bludgeoning, Channel +x Dice'),
  CatalogItem(id: 'm_greatsword', name: 'Greatsword', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 3, description: 'Combat 3, Burst, Sharp, Reach 1, Cleave, Parry'),
  CatalogItem(id: 'm_enchanted_blade', name: 'Enchanted Blade', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 3, description: 'Combat 2, Burst, Sharp, Parry, Channel +x Dice'),
  CatalogItem(id: 'm_great_axe', name: 'Great Axe', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 4, description: 'Combat 4, Burst, Cumbersome, Sharp, Cleave'),
  CatalogItem(id: 'm_waspsting', name: 'Waspsting', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.rare, rank: 2, description: 'Combat 2, Sharp, Effortless'),
  CatalogItem(id: 'm_lothors_destiny', name: "Lothor's Destiny", category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.rare, rank: 2, description: 'Combat 2, Malacyte Enchantment'),
  CatalogItem(id: 'm_huntsmans_reach', name: "Huntsman's Reach", category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.rare, rank: 2, description: 'Combat 3, Balanced, Sharp, Reach 1'),
  CatalogItem(id: 'm_glaive', name: 'Glaive', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.rare, rank: 3, description: 'Combat 3, Sharp, Cleave, Reach 2'),
  CatalogItem(id: 'm_staff_of_harmony', name: 'Staff Of Harmony', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.rare, rank: 3, description: 'Combat 2, Malacyte Stability'),
  CatalogItem(id: 'm_ignis_sceptre', name: 'Ignis Sceptre', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.rare, rank: 3, description: 'Combat 2, Spell Fireball'),
  CatalogItem(id: 'm_plethrum', name: 'Plethrum', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.rare, rank: 3, description: 'Combat 2, Sharp, Reach 2, Light'),
  CatalogItem(id: 'm_starburst_staff', name: 'Starburst Staff', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.rare, rank: 3, description: 'Combat 2, Regen 1 (Magic), Spell Energy Burst'),
  CatalogItem(id: 'm_cleaver_of_misfortune', name: 'Cleaver Of Misfortune', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.rare, rank: 4, description: 'Combat 3, Burst, Cleave, Vicious, Reach 1, Forbidden Channel Curse'),
  CatalogItem(id: 'm_lowicks_axe', name: "Lowick's Axe", category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.rare, rank: 4, description: 'Combat 2, Burst, Channel Piercing'),
  CatalogItem(id: 'm_titanbane', name: 'Titanbane', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.rare, rank: 4, description: 'Combat 4, Burst, Vicious, Sharp, Preparation, Reach 3'),
  CatalogItem(id: 'm_efreets_heart', name: "Efreet's Heart", category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.rare, rank: 4, description: 'Combat 3, Burst, Burning, Sharp, Parry'),
  CatalogItem(id: 'm_lordsblade', name: 'Lordsblade', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.rare, rank: 4, description: 'Combat 3, Burst, Re-roll, Sharp, Parry'),
  CatalogItem(id: 'm_dragonslayer', name: 'Dragonslayer', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.rare, rank: 4, description: 'Combat 5, Vicious, Sharp, Immunity Terrifying'),
  CatalogItem(id: 'm_blade_of_carnage', name: 'Blade Of Carnage', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.rare, rank: 5, description: 'Combat 5, Cleave, Sharp, Reach 1'),
  CatalogItem(id: 'm_envoys_message', name: "Envoy's Message", category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.rare, rank: 5, description: 'Combat 3, Burst, Bludgeoning, Channel Reach 5'),
  CatalogItem(id: 'm_disarming_staff', name: 'Disarming Staff', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat 2, Reach 1, Plunderer, Indestructable'),
  CatalogItem(id: 'm_bittz_hammer', name: 'Bittz Hammer', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat 2, Quickstrike, Relentless'),
  CatalogItem(id: 'm_honed_long_sword', name: 'Honed Long Sword', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat 3, Parry, Sharp, Indestructable'),
  CatalogItem(id: 'm_arcane_steel', name: 'Arcane Steel', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat 3, Sharp, Indestructable, Channel +x Dice'),
  CatalogItem(id: 'm_calamitous_caber', name: 'Calamitous Caber', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat 3, Burst, Reach 2, Balanced, Bludgeoning'),
  CatalogItem(id: 'm_ethereal_edge', name: 'Ethereal Edge', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat 3, Reach 1, Sharp, Vicious, Volatile'),
  CatalogItem(id: 'm_spelleater', name: 'Spelleater', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat 2, Vicious, Vampiric Magic Pegs'),
  CatalogItem(id: 'm_honed_war_axe', name: 'Honed War Axe', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat 3, Vicious, Sharp, Indestructable'),
  CatalogItem(id: 'm_necrotic_censer', name: 'Necrotic Censer', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat 3, Reach 2, Poison, Volatile, Bludgeoning'),
  CatalogItem(id: 'm_shilleagh', name: 'Shilleagh', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat 2, Burst, First Strike, Bludgeoning'),
  CatalogItem(id: 'm_viperfang', name: 'Viperfang', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat 3, Poison, Vicious'),
  CatalogItem(id: 'm_hellfire_blade', name: 'Hellfire Blade', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat 3, Burning, Vicious, Terrifying, Indestructable'),
  CatalogItem(id: 'm_reapers_riposte', name: "Reaper's Riposte", category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat 2, Re-roll, Parry, Retaliation'),
  CatalogItem(id: 'm_bladed_shield', name: 'Bladed Shield', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat 3, Armour +1, Sharp, Indestructable'),
  CatalogItem(id: 'm_crafted_great_sword', name: 'Crafted Great Sword', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat 3, Burst, Sharp, Reach 1, Cleave, Parry'),
  CatalogItem(id: 'm_keltic_falchion', name: 'Keltic Falchion', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat 3, Quickstrike, Cleave, Indestructable'),
  CatalogItem(id: 'm_crafted_great_axe', name: 'Crafted Great Axe', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat 4, Burst, Cumbersome, Sharp, Cleave'),
  CatalogItem(id: 'm_sentient_scimitar', name: 'Sentient Scimitar', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat 2, Burst, Sharp, Channel Reactive'),
  CatalogItem(id: 'm_starstrike_flail', name: 'Starstrike Flail', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat 3, Vicious, Entangling, Sharp, Reach 1'),
  CatalogItem(id: 'm_blade_of_momentum', name: 'Blade of Momentum', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat 2, First Strike, Sharp, Channel Hit and Run'),
  CatalogItem(id: 'm_vampiric_blade', name: 'Vampiric Blade', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat 3, Burst, Vampiric Health, Reach 1, Cleave, Sharp'),
  CatalogItem(id: 'm_bewitched_blade', name: 'Bewitched Blade', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat 2, Burst, Sharp, Parry, Channel +x Dice'),
  CatalogItem(id: 'm_astral_arbiter', name: 'Astral Arbiter', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat 4, Sharp, Spell Energy Burst, Spell Focused Energy, Indestructable'),
  CatalogItem(id: 'm_sword_of_tephysus', name: 'Sword of Tephysus', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat 4, Sharp, Light, Cleave, Reach 1, Indestructable, Channel Piercing'),
  CatalogItem(id: 'm_natures_fury', name: "Nature's Fury", category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat 3, Vicious, Bludgeoning, Frenzy 3'),
  CatalogItem(id: 'm_uncanny_occulus', name: 'Uncanny Occulus', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat 3, Once per game call upon Otherworldly power. See Maw rulebook.'),
  CatalogItem(id: 'm_ascendant_blades', name: 'Ascendant Blades', category: 'Weapons - Melee', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat 4, Parry, Quickstrike, Vicious, Reach 2, Indestructable'),

  // ─── Weapons - Ranged ─────────────────────────────────────────────────────
  CatalogItem(id: 'rng_sling', name: 'Sling', category: 'Weapons - Ranged', color: ItemColor.blue, rarity: Rarity.common, rank: 1, description: 'Combat (1), Bludgeoning'),
  CatalogItem(id: 'rng_bolas', name: 'Bolas', category: 'Weapons - Ranged', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 1, description: 'Combat (2), Entangling, Vicious, discard'),
  CatalogItem(id: 'rng_blowgun', name: 'Blowgun', category: 'Weapons - Ranged', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 1, description: 'Combat (2)'),
  CatalogItem(id: 'rng_short_bow', name: 'Short Bow', category: 'Weapons - Ranged', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 1, description: 'Combat (1,2)'),
  CatalogItem(id: 'rng_crossbow', name: 'Crossbow', category: 'Weapons - Ranged', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 1, description: 'Combat (2,2,1), Preparation'),
  CatalogItem(id: 'rng_throwing_stars', name: 'Throwing Stars', category: 'Weapons - Ranged', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 2, description: 'Combat (2), Effortless'),
  CatalogItem(id: 'rng_composite_longbow', name: 'Composite Longbow', category: 'Weapons - Ranged', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 2, description: 'Combat (1,3,3)'),
  CatalogItem(id: 'rng_heavy_crossbow', name: 'Heavy Crossbow', category: 'Weapons - Ranged', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 2, description: 'Combat (3,3,2), Preparation'),
  CatalogItem(id: 'rng_flintlock_pistol', name: 'Flintlock Pistol', category: 'Weapons - Ranged', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 3, description: 'Combat (4), Loud, Unreliable'),
  CatalogItem(id: 'rng_issen_oil', name: 'Issen Oil', category: 'Weapons - Ranged', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 3, description: 'Combat (2), Burning'),
  CatalogItem(id: 'rng_flintlock_rifle', name: 'Flintlock Rifle', category: 'Weapons - Ranged', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 3, description: 'Combat (2,4,3), Loud, Preparation, Unreliable'),
  CatalogItem(id: 'rng_merutan_longbow', name: 'Merutan Longbow', category: 'Weapons - Ranged', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 3, description: 'Combat (0,4,3), Cumbersome, Bludgeoning'),
  CatalogItem(id: 'rng_the_supernova', name: 'The Supernova', category: 'Weapons - Ranged', color: ItemColor.blue, rarity: Rarity.rare, rank: 5, description: 'Combat (3,5,4), Loud, Preparation'),
  CatalogItem(id: 'rng_blunderbuss', name: 'Blunderbuss', category: 'Weapons - Ranged', color: ItemColor.blue, rarity: Rarity.rare, rank: 2, description: 'Combat (3,3), Burst, Loud, Preparation, Unreliable'),
  CatalogItem(id: 'rng_explosives', name: 'Explosives', category: 'Weapons - Ranged', color: ItemColor.blue, rarity: Rarity.rare, rank: 2, description: 'Combat (4), Burst, Loud, Discard, Effortless'),
  CatalogItem(id: 'rng_enchanted_longbow', name: 'Enchanted Longbow', category: 'Weapons - Ranged', color: ItemColor.blue, rarity: Rarity.rare, rank: 3, description: 'Combat (1,3,3), Channel +x Dice'),
  CatalogItem(id: 'rng_krakens_doom', name: "Kraken's Doom", category: 'Weapons - Ranged', color: ItemColor.blue, rarity: Rarity.rare, rank: 4, description: 'Combat (3,4,4), Preparation'),
  CatalogItem(id: 'rng_persuader', name: 'Persuader', category: 'Weapons - Ranged', color: ItemColor.blue, rarity: Rarity.rare, rank: 4, description: 'Combat (4,2), Loud'),
  CatalogItem(id: 'rng_wyrmbreath_pistol', name: 'Wyrmbreath Pistol', category: 'Weapons - Ranged', color: ItemColor.blue, rarity: Rarity.rare, rank: 4, description: 'Combat (4), Burst, Burning'),
  CatalogItem(id: 'rng_eid_short_bow', name: 'Eid Short Bow', category: 'Weapons - Ranged', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat (1,2), Channel +x Dice'),
  CatalogItem(id: 'rng_liberator_of_souls', name: 'Liberator of Souls', category: 'Weapons - Ranged', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat (2,2), Channel Piercing vs Revenants'),
  CatalogItem(id: 'rng_mastercrafted_bow', name: 'Mastercrafted Bow', category: 'Weapons - Ranged', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat (2,3,2), Re-roll'),
  CatalogItem(id: 'rng_mechanical_musket', name: 'Mechanical Musket', category: 'Weapons - Ranged', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat (3,4,3), Unreliable, Noisy'),
  CatalogItem(id: 'rng_soul_siphon', name: 'Soul Siphon', category: 'Weapons - Ranged', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Combat (2), Vampiric Health/Skill/Magic peg, Vicious'),

  // ─── Ammo ──────────────────────────────────────────────────────────────────
  CatalogItem(id: 'amm_arrows', name: 'Arrows', category: 'Ammo', color: ItemColor.blue, rarity: Rarity.common, rank: 1, description: 'Ammo'),
  CatalogItem(id: 'amm_sharp_arrows', name: 'Sharp Arrows', category: 'Ammo', color: ItemColor.blue, rarity: Rarity.common, rank: 1, description: 'Sharp, Ammo'),
  CatalogItem(id: 'amm_poison_darts', name: 'Poison Darts', category: 'Ammo', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 1, description: 'Poison, Ammo'),
  CatalogItem(id: 'amm_shot', name: 'Shot', category: 'Ammo', color: ItemColor.blue, rarity: Rarity.common, rank: 1, description: 'Ammo'),
  CatalogItem(id: 'amm_fire_arrows', name: 'Fire Arrows', category: 'Ammo', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 1, description: 'Burning, Ammo'),
  CatalogItem(id: 'amm_beastslayer_arrows', name: 'Beastslayer Arrows', category: 'Ammo', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 1, description: 'Add 1 Dice, Sharp, Ammo'),
  CatalogItem(id: 'amm_harpoon', name: 'Harpoon', category: 'Ammo', color: ItemColor.blue, rarity: Rarity.uncommon, rank: 1, description: 'Sharp, Ignore Armour, Ammo, discard'),
  CatalogItem(id: 'amm_hawkeye_arrows', name: 'Hawkeye Arrows', category: 'Ammo', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Sharp, Hawkeye'),
  CatalogItem(id: 'amm_poison_arrows', name: 'Poison Arrows', category: 'Ammo', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Sharp, Poison'),
  CatalogItem(id: 'amm_web_arrows', name: 'Web Arrows', category: 'Ammo', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Entangling'),
  CatalogItem(id: 'amm_barbed_arrows', name: 'Barbed Arrows', category: 'Ammo', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Sharp, Vicious'),
  CatalogItem(id: 'amm_blast_shot', name: 'Blast Shot', category: 'Ammo', color: ItemColor.blue, rarity: Rarity.exclusive, rank: 0, description: 'Burning, (+1) Blast'),

  // ─── Armour ────────────────────────────────────────────────────────────────
  CatalogItem(id: 'arm_helmet', name: 'Helmet', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.common, rank: 1, description: 'Immunity to Bludgeoning'),
  CatalogItem(id: 'arm_plate_gauntlets', name: 'Plate Gauntlets', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.common, rank: 1, description: 'Parry'),
  CatalogItem(id: 'arm_avian_seal', name: 'Avian Seal', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.common, rank: 1, description: 'Channel Re-roll'),
  CatalogItem(id: 'arm_traveling_cloak', name: 'Traveling Cloak', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.common, rank: 1, description: 'Camouflage 2'),
  CatalogItem(id: 'arm_bladed_bracers', name: 'Bladed Bracers', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.uncommon, rank: 1, description: 'Unarmed +1, Sharp'),
  CatalogItem(id: 'arm_leather_armour', name: 'Leather Armour', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.common, rank: 1, description: 'Defensive Re-roll'),
  CatalogItem(id: 'arm_tough_old_boots', name: 'Tough Old Boots', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.common, rank: 1, description: 'Rough Ground -1'),
  CatalogItem(id: 'arm_wyrmtooth_necklace', name: 'Wyrmtooth Necklace', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.common, rank: 1, description: 'Intimidating 1'),
  CatalogItem(id: 'arm_ice_trekkers', name: 'Ice Trekkers', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.common, rank: 1, description: 'Rough Ground -1'),
  CatalogItem(id: 'arm_frost_amulet', name: 'Frost Amulet', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.uncommon, rank: 1, description: 'Immune Burning'),
  CatalogItem(id: 'arm_dream_catcher', name: 'Dream Catcher', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.uncommon, rank: 1, description: 'Immune Curse'),
  CatalogItem(id: 'arm_studded_leather_armour', name: 'Studded Leather Armour', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.uncommon, rank: 1, description: 'Armour 1'),
  CatalogItem(id: 'arm_studded_leather_t2', name: 'Studded Leather Armour (T2)', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.uncommon, rank: 2, description: 'Armour 1'),
  CatalogItem(id: 'arm_silver_tongue_slacks', name: 'Silver-Tongue Slacks', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.uncommon, rank: 2, description: 'Persuasion 2'),
  CatalogItem(id: 'arm_chakri', name: 'Chakri', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.uncommon, rank: 2, description: 'Retaliation, Parry'),
  CatalogItem(id: 'arm_night_shroud', name: 'Night Shroud', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.uncommon, rank: 2, description: 'Ambush 2, Camouflage'),
  CatalogItem(id: 'arm_keepers_robes', name: "Keeper's Robes", category: 'Armour', color: ItemColor.yellow, rarity: Rarity.uncommon, rank: 2, description: 'Magical Armour 1'),
  CatalogItem(id: 'arm_jade_amulet', name: 'Jade Amulet', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.uncommon, rank: 2, description: 'Magical Armour 1'),
  CatalogItem(id: 'arm_chainmail_armour', name: 'Chainmail Armour', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.uncommon, rank: 2, description: 'Armour 1, Defensive Re-roll'),
  CatalogItem(id: 'arm_quiver', name: 'Quiver', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.uncommon, rank: 3, description: 'Infinite Regular Arrow Ammo'),
  CatalogItem(id: 'arm_amulet_of_magic_reserves', name: 'Amulet of Magic Reserves', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.uncommon, rank: 3, description: 'Regen 1 (Magic)'),
  CatalogItem(id: 'arm_breastplate_armour', name: 'Breastplate Armour', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.uncommon, rank: 4, description: 'Armour 2'),
  CatalogItem(id: 'arm_fullplate_armour', name: 'Fullplate Armour', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.uncommon, rank: 5, description: 'Armour 2, Combat 2, Immune Sharp, Defensive Re-roll'),
  CatalogItem(id: 'arm_night_sight_goggles', name: 'Night Sight Goggles', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.rare, rank: 1, description: 'Night Sight'),
  CatalogItem(id: 'arm_forbidden_talisman', name: 'Forbidden Talisman', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.rare, rank: 1, description: 'Forbidden Arts 1'),
  CatalogItem(id: 'arm_terrifying_mask', name: 'Terrifying Mask', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.rare, rank: 1, description: 'Terrifying'),
  CatalogItem(id: 'arm_spellweavers_cowl', name: "Spellweaver's Cowl", category: 'Armour', color: ItemColor.yellow, rarity: Rarity.rare, rank: 2, description: 'Fortified Mind 2'),
  CatalogItem(id: 'arm_skystriders', name: 'Skystriders', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.rare, rank: 2, description: 'Spell Jump'),
  CatalogItem(id: 'arm_stygian_cloak', name: 'Stygian Cloak', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.rare, rank: 2, description: 'Spell Spectral Shroud'),
  CatalogItem(id: 'arm_earthbound_boots', name: 'Earthbound Boots', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.rare, rank: 2, description: 'Steady 2'),
  CatalogItem(id: 'arm_crag_troll_hide', name: 'Crag Troll Hide', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.rare, rank: 2, description: 'Armor 1, Camouflage'),
  CatalogItem(id: 'arm_boundless_bracers', name: 'Boundless Bracers', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.rare, rank: 2, description: 'Channel x Unarmed Combat'),
  CatalogItem(id: 'arm_casque_of_warding', name: 'Casque Of Warding', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.rare, rank: 2, description: 'Magical Armor 1'),
  CatalogItem(id: 'arm_phantom_veil', name: 'Phantom Veil', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.rare, rank: 3, description: 'Spell Invisibility'),
  CatalogItem(id: 'arm_trailblazers', name: 'Trailblazers', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.rare, rank: 3, description: 'Channel Speed 2, Lasting effect'),
  CatalogItem(id: 'arm_rift_ring', name: 'Rift Ring', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.rare, rank: 3, description: 'Spell Dimensional Portal'),
  CatalogItem(id: 'arm_kharastad_regalia', name: 'Kharastad Regalia', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.rare, rank: 3, description: 'Armor 1, Defensive Reroll, Intimidating 2'),
  CatalogItem(id: 'arm_sentinel_of_virtue', name: 'Sentinel Of Virtue', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.rare, rank: 3, description: 'Armor 1, Malacyte Stability'),
  CatalogItem(id: 'arm_boots_of_celerity', name: 'Boots Of Celerity', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.rare, rank: 3, description: 'Channel Restore Action'),
  CatalogItem(id: 'arm_halo_of_tranquility', name: 'Halo of Tranquility', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.rare, rank: 4, description: 'Channel Lull 1'),
  CatalogItem(id: 'arm_multiversal_cap', name: 'Multiversal Cap', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.rare, rank: 4, description: 'Spell Summoning'),
  CatalogItem(id: 'arm_vestment_of_sanctuary', name: 'Vestment of Sanctuary', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.rare, rank: 4, description: 'Magical Armor 2'),
  CatalogItem(id: 'arm_shifting_skin', name: 'Shifting Skin', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.rare, rank: 4, description: 'Magical Armor 2, Combat (2), Channel, Regen 1 (Magic), Spell Illusion, Malacytic Conduit'),
  CatalogItem(id: 'arm_graam_medallion', name: 'Graam Medallion', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.rare, rank: 5, description: 'Add 2 magic pegs'),
  CatalogItem(id: 'arm_leather_hat', name: 'Leather Hat', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.exclusive, rank: 0, description: 'Defensive Re-roll'),
  CatalogItem(id: 'arm_herbalists_cloak', name: "Herbalist's Cloak", category: 'Armour', color: ItemColor.yellow, rarity: Rarity.exclusive, rank: 0, description: 'Natural Remedies 2, Immunity to Poison'),
  CatalogItem(id: 'arm_makeshift_wings', name: 'Makeshift Wings', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.exclusive, rank: 0, description: '3->2 Scramble'),
  CatalogItem(id: 'arm_cloak_of_cloning', name: 'Cloak of Cloning', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.exclusive, rank: 0, description: 'Camouflage, Advanced Illusion'),
  CatalogItem(id: 'arm_keltmail_armour', name: 'Keltmail Armour', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.exclusive, rank: 0, description: 'Armour 1, Immune Sharp and Bludgeoning, Indestructable'),
  CatalogItem(id: 'arm_honed_leather_armour', name: 'Honed Leather Armour', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.exclusive, rank: 0, description: 'Defensive Re-roll, Reflexes 1'),
  CatalogItem(id: 'arm_spiked_armour', name: 'Spiked Armour', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.exclusive, rank: 0, description: 'Armour 1, Retaliation, Combat 2 Burst'),
  CatalogItem(id: 'arm_robes_of_invulnerability', name: 'Robes of Invulnerability', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.exclusive, rank: 0, description: 'Impervious 3'),
  CatalogItem(id: 'arm_crafted_breastplate', name: 'Crafted Breastplate Armour', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.exclusive, rank: 0, description: 'Armour 2'),
  CatalogItem(id: 'arm_curative_cuirass', name: 'Curative Cuirass', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.exclusive, rank: 0, description: 'Armour 1, Spend 2 Actions/Resting: Gain 1 Health Peg'),
  CatalogItem(id: 'arm_refined_robes', name: 'Refined Robes', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.exclusive, rank: 0, description: 'Magical Armour 1, Regen 1 (Magic)'),
  CatalogItem(id: 'arm_daemon_mantle', name: 'Daemon Mantle', category: 'Armour', color: ItemColor.yellow, rarity: Rarity.exclusive, rank: 0, description: 'Cast Rearrange Cells with X=5, no pegs spent, no Magic Die rolled. Once per Quest.'),

  // ─── Shield ────────────────────────────────────────────────────────────────
  CatalogItem(id: 'shl_small_shield', name: 'Small Shield', category: 'Shield', color: ItemColor.yellow, rarity: Rarity.common, rank: 1, description: 'Defensive Re-roll'),
  CatalogItem(id: 'shl_large_shield', name: 'Large Shield', category: 'Shield', color: ItemColor.yellow, rarity: Rarity.uncommon, rank: 1, description: 'Add 1 Armour'),

  // ─── Other ─────────────────────────────────────────────────────────────────
  CatalogItem(id: 'oth_scroll_of_affliction', name: 'Scroll of Affliction', category: 'Other', color: ItemColor.red, rarity: Rarity.common, rank: 1, description: 'Spell Curse'),
  CatalogItem(id: 'oth_map', name: 'Map', category: 'Other', color: ItemColor.red, rarity: Rarity.common, rank: 1, description: 'Tracking 2'),
  CatalogItem(id: 'oth_caltrops', name: 'Caltrops', category: 'Other', color: ItemColor.red, rarity: Rarity.common, rank: 1, description: 'Combat 1, Entangling, Sharp'),
  CatalogItem(id: 'oth_purifona_root', name: 'Purifona Root', category: 'Other', color: ItemColor.red, rarity: Rarity.common, rank: 1, description: 'Purification 1'),
  CatalogItem(id: 'oth_blessed_water', name: 'Blessed Water', category: 'Other', color: ItemColor.red, rarity: Rarity.uncommon, rank: 1, description: 'Combat 2/(2), Ignore Armor, only against Revenants'),
  CatalogItem(id: 'oth_rat_tail_bracelet', name: 'Rat Tail Bracelet', category: 'Other', color: ItemColor.red, rarity: Rarity.uncommon, rank: 1, description: 'Re-roll'),
  CatalogItem(id: 'oth_rope', name: 'Rope', category: 'Other', color: ItemColor.red, rarity: Rarity.common, rank: 1, description: 'See rules in rulebook p154'),
  CatalogItem(id: 'oth_old_book', name: 'Old Book', category: 'Other', color: ItemColor.red, rarity: Rarity.common, rank: 1, description: 'See table in rulebook p151'),
  CatalogItem(id: 'oth_scrimshaw_bear_tooth', name: 'Scrimshaw Bear Tooth', category: 'Other', color: ItemColor.red, rarity: Rarity.common, rank: 1, description: 'Re-roll, discard'),
  CatalogItem(id: 'oth_bear_trap', name: 'Bear Trap', category: 'Other', color: ItemColor.red, rarity: Rarity.uncommon, rank: 1, description: 'Combat 2, Sharp'),
  CatalogItem(id: 'oth_hunting_gear', name: 'Hunting Gear', category: 'Other', color: ItemColor.red, rarity: Rarity.uncommon, rank: 1, description: 'One with Nature 1'),
  CatalogItem(id: 'oth_refract_lamp', name: 'Refract Lamp', category: 'Other', color: ItemColor.red, rarity: Rarity.uncommon, rank: 1, description: 'Refract'),
  CatalogItem(id: 'oth_pan_pipes', name: 'Pan Pipes', category: 'Other', color: ItemColor.red, rarity: Rarity.uncommon, rank: 1, description: 'Distraction 1'),
  CatalogItem(id: 'oth_camping_gear', name: 'Camping Gear', category: 'Other', color: ItemColor.red, rarity: Rarity.uncommon, rank: 1, description: 'Re-roll all Wilderness rolls'),
  CatalogItem(id: 'oth_wand_of_impedence', name: 'Wand of Impedence', category: 'Other', color: ItemColor.red, rarity: Rarity.uncommon, rank: 2, description: 'Stun'),
  CatalogItem(id: 'oth_energy_wand', name: 'Energy Wand', category: 'Other', color: ItemColor.red, rarity: Rarity.uncommon, rank: 2, description: 'Spell Focused Energy'),
  CatalogItem(id: 'oth_crafting_tools', name: 'Crafting Tools', category: 'Other', color: ItemColor.red, rarity: Rarity.uncommon, rank: 2, description: 'Smithing 1'),
  CatalogItem(id: 'oth_lockpicks', name: 'Lockpicks', category: 'Other', color: ItemColor.red, rarity: Rarity.uncommon, rank: 2, description: 'Tricks of the Trade 1'),
  CatalogItem(id: 'oth_flute', name: 'Flute', category: 'Other', color: ItemColor.red, rarity: Rarity.uncommon, rank: 2, description: 'Persuasion 2'),
  CatalogItem(id: 'oth_doorbuster', name: 'Doorbuster', category: 'Other', color: ItemColor.red, rarity: Rarity.uncommon, rank: 2, description: 'Unarmed +3 against Terrain, Preparation'),
  CatalogItem(id: 'oth_sanguine_stone', name: 'Sanguine Stone', category: 'Other', color: ItemColor.red, rarity: Rarity.uncommon, rank: 2, description: 'Channel Recover 1 Health Peg'),
  CatalogItem(id: 'oth_sledge_of_burden', name: 'Sledge of Burden', category: 'Other', color: ItemColor.red, rarity: Rarity.uncommon, rank: 2, description: 'Size +1 when moving furniture'),
  CatalogItem(id: 'oth_simulacrum', name: 'Simulacrum', category: 'Other', color: ItemColor.red, rarity: Rarity.uncommon, rank: 2, description: 'Spell Curse'),
  CatalogItem(id: 'oth_lute', name: 'Lute', category: 'Other', color: ItemColor.red, rarity: Rarity.uncommon, rank: 3, description: 'Entertainer 2'),
  CatalogItem(id: 'oth_eternity_vessel', name: 'Eternity Vessel', category: 'Other', color: ItemColor.red, rarity: Rarity.uncommon, rank: 4, description: 'See Forbidden Creed rulebook'),
  CatalogItem(id: 'oth_cubes_of_fate', name: 'The Cubes of Fate', category: 'Other', color: ItemColor.red, rarity: Rarity.uncommon, rank: 5, description: 'Re-roll, Hazardous (Curse)'),
  CatalogItem(id: 'oth_book', name: 'Book', category: 'Other', color: ItemColor.red, rarity: Rarity.rare, rank: 1, description: 'See table in rulebook'),
  CatalogItem(id: 'oth_skeleton_key', name: 'Skeleton Key', category: 'Other', color: ItemColor.red, rarity: Rarity.rare, rank: 2, description: 'Spell Open Door'),
  CatalogItem(id: 'oth_prism_of_protection', name: 'Prism of Protection', category: 'Other', color: ItemColor.red, rarity: Rarity.rare, rank: 2, description: 'Channel to negate reach/ranged attack, Lasting effect'),
  CatalogItem(id: 'oth_revered_effigy', name: 'Revered Effigy', category: 'Other', color: ItemColor.red, rarity: Rarity.rare, rank: 2, description: 'Inspiring 3'),
  CatalogItem(id: 'oth_aetherflux', name: 'Aetherflux', category: 'Other', color: ItemColor.red, rarity: Rarity.rare, rank: 2, description: 'Resting: Reduce Dread by 2'),
  CatalogItem(id: 'oth_vengeance_ward', name: 'Vengeance Ward', category: 'Other', color: ItemColor.red, rarity: Rarity.rare, rank: 2, description: 'Add 1 Armour, Channel Retaliation'),
  CatalogItem(id: 'oth_athlum_rod', name: 'Athlum Rod', category: 'Other', color: ItemColor.red, rarity: Rarity.rare, rank: 3, description: 'Add 1 magic peg, Light'),
  CatalogItem(id: 'oth_lichs_libram', name: "Lich's Libram", category: 'Other', color: ItemColor.red, rarity: Rarity.rare, rank: 3, description: 'Spell Raise Dead'),
  CatalogItem(id: 'oth_flying_carpet', name: 'Flying Carpet', category: 'Other', color: ItemColor.red, rarity: Rarity.rare, rank: 3, description: 'Spell Levitation'),
  CatalogItem(id: 'oth_mystic_grimoire', name: 'Mystic Grimoire', category: 'Other', color: ItemColor.red, rarity: Rarity.rare, rank: 3, description: 'Special: Learn spells one rank higher than character rank'),
  CatalogItem(id: 'oth_maladaars_almanac', name: "Maladaar's Almanac", category: 'Other', color: ItemColor.red, rarity: Rarity.rare, rank: 3, description: 'Special: Gain one spell per character rank'),
  CatalogItem(id: 'oth_serendipitous_sack', name: 'Serendipitous Sack', category: 'Other', color: ItemColor.red, rarity: Rarity.rare, rank: 4, description: 'Spell Conjuration'),
  CatalogItem(id: 'oth_necrotic_fluids', name: 'Necrotic Fluids', category: 'Other', color: ItemColor.red, rarity: Rarity.exclusive, rank: 0, description: 'Crafting Material'),
  CatalogItem(id: 'oth_sacrificium', name: 'Sacrificium', category: 'Other', color: ItemColor.red, rarity: Rarity.exclusive, rank: 0, description: 'Healing Hands, Hazardous Lose 1 Health Peg'),
  CatalogItem(id: 'oth_warrior_totem', name: 'Warrior Totem', category: 'Other', color: ItemColor.red, rarity: Rarity.exclusive, rank: 0, description: 'Frenzy 2'),
  CatalogItem(id: 'oth_protection_orb', name: 'Protection Orb', category: 'Other', color: ItemColor.red, rarity: Rarity.exclusive, rank: 0, description: 'Spell Cocoon'),
  CatalogItem(id: 'oth_grail_of_the_gods', name: 'Grail of the Gods', category: 'Other', color: ItemColor.red, rarity: Rarity.exclusive, rank: 0, description: 'Restore 1 Health Peg'),
  CatalogItem(id: 'oth_scepter_of_dominion', name: 'Scepter of Dominion', category: 'Other', color: ItemColor.red, rarity: Rarity.exclusive, rank: 0, description: 'Persuasion 3, 2x Action restore 1 skill Peg. Persuade any character to do anything.'),
  CatalogItem(id: 'oth_abyssal_trophy', name: 'Abyssal Trophy', category: 'Other', color: ItemColor.red, rarity: Rarity.exclusive, rank: 0, description: 'The user may Re-roll attacks and effects and is terrifying vs otherworldly'),
  CatalogItem(id: 'oth_light_in_the_darkness', name: 'Light in the Darkness', category: 'Other', color: ItemColor.red, rarity: Rarity.exclusive, rank: 0, description: 'Light, Character may be used as a Summoning Point. Forbidden Channel Regen 1 (Skill)'),

  // ─── Crafting Materials ────────────────────────────────────────────────────
  CatalogItem(id: 'cft_wood', name: 'Wood', category: 'Crafting Materials', color: ItemColor.grey, rarity: Rarity.common, rank: 1, description: 'Crafting Material'),
  CatalogItem(id: 'cft_textile', name: 'Textile', category: 'Crafting Materials', color: ItemColor.grey, rarity: Rarity.common, rank: 1, description: 'Crafting Material'),
  CatalogItem(id: 'cft_steel', name: 'Steel', category: 'Crafting Materials', color: ItemColor.grey, rarity: Rarity.common, rank: 1, description: 'Crafting Material'),
  CatalogItem(id: 'cft_herbs', name: 'Herbs', category: 'Crafting Materials', color: ItemColor.grey, rarity: Rarity.common, rank: 1, description: 'Crafting Material'),
  CatalogItem(id: 'cft_fungus', name: 'Fungus', category: 'Crafting Materials', color: ItemColor.grey, rarity: Rarity.common, rank: 1, description: 'Crafting Material'),
  CatalogItem(id: 'cft_minerals', name: 'Minerals', category: 'Crafting Materials', color: ItemColor.grey, rarity: Rarity.common, rank: 1, description: 'Crafting Material'),
  CatalogItem(id: 'cft_riches', name: 'Riches', category: 'Crafting Materials', color: ItemColor.grey, rarity: Rarity.common, rank: 1, description: 'Crafting Material'),
  CatalogItem(id: 'cft_serpent_venom', name: 'Serpent Venom', category: 'Crafting Materials', color: ItemColor.grey, rarity: Rarity.uncommon, rank: 1, description: 'Crafting Material'),
  CatalogItem(id: 'cft_keltic_steel', name: 'Keltic Steel', category: 'Crafting Materials', color: ItemColor.grey, rarity: Rarity.uncommon, rank: 2, description: 'Crafting Material'),
  CatalogItem(id: 'cft_powered_drakon_bone', name: 'Powered Drakon Bone', category: 'Crafting Materials', color: ItemColor.grey, rarity: Rarity.uncommon, rank: 2, description: 'Crafting Material'),
  CatalogItem(id: 'cft_graam_ore', name: 'Graam Ore', category: 'Crafting Materials', color: ItemColor.grey, rarity: Rarity.uncommon, rank: 2, description: 'Crafting Material'),
  CatalogItem(id: 'cft_issen_oil', name: 'Issen Oil', category: 'Crafting Materials', color: ItemColor.grey, rarity: Rarity.uncommon, rank: 3, description: 'Crafting Material'),
  CatalogItem(id: 'cft_alary_carapace', name: 'Alary Carapace', category: 'Crafting Materials', color: ItemColor.grey, rarity: Rarity.rare, rank: 3, description: 'Crafting Material'),
  CatalogItem(id: 'cft_extract_of_maladite', name: 'Extract of Maladite', category: 'Crafting Materials', color: ItemColor.grey, rarity: Rarity.rare, rank: 3, description: 'Crafting Material'),

  // ─── Companion Totems ──────────────────────────────────────────────────────
  CatalogItem(id: 'tot_tiliketi_totem', name: "Tilik'Eti Totem", category: 'Companion Totems', color: ItemColor.purple, rarity: Rarity.uncommon, rank: 2, description: "Summoning (Tilik'Eti)"),
  CatalogItem(id: 'tot_nynn_totem', name: 'Nynn Totem', category: 'Companion Totems', color: ItemColor.purple, rarity: Rarity.uncommon, rank: 2, description: 'Summoning (Nynn)'),
  CatalogItem(id: 'tot_reeki_totem', name: 'Reeki Totem', category: 'Companion Totems', color: ItemColor.purple, rarity: Rarity.uncommon, rank: 3, description: 'Summoning (Reeki)'),
  CatalogItem(id: 'tot_miri_totem', name: 'Miri Totem', category: 'Companion Totems', color: ItemColor.purple, rarity: Rarity.uncommon, rank: 3, description: 'Summoning (Miri)'),
  CatalogItem(id: 'tot_astet_totem', name: 'Astet Totem', category: 'Companion Totems', color: ItemColor.purple, rarity: Rarity.uncommon, rank: 3, description: 'Summoning (Astet)'),

  // ─── Restoratives ──────────────────────────────────────────────────────────
  CatalogItem(id: 'rst_morsel', name: 'Morsel', category: 'Restoratives', color: ItemColor.red, rarity: Rarity.common, rank: 1, description: 'Resting: Restore +1 Health Peg'),
  CatalogItem(id: 'rst_remedy', name: 'Remedy', category: 'Restoratives', color: ItemColor.red, rarity: Rarity.uncommon, rank: 1, description: 'Remove Poisoned or Wounded token'),
  CatalogItem(id: 'rst_mindbloom', name: 'Mindbloom', category: 'Restoratives', color: ItemColor.red, rarity: Rarity.common, rank: 1, description: 'Resting: Restore +1 Skill Peg'),
  CatalogItem(id: 'rst_provisions', name: 'Provisions', category: 'Restoratives', color: ItemColor.red, rarity: Rarity.common, rank: 1, description: 'Resting: Restore +2 Health Pegs'),
  CatalogItem(id: 'rst_arcanum_kouse', name: 'Arcanum Kouse', category: 'Restoratives', color: ItemColor.red, rarity: Rarity.uncommon, rank: 1, description: 'Restore 2 Magic Pegs'),
  CatalogItem(id: 'rst_herbs', name: 'Herbs', category: 'Restoratives', color: ItemColor.red, rarity: Rarity.common, rank: 1, description: 'Resting: Restore +1 Health Peg'),
  CatalogItem(id: 'rst_fungus', name: 'Fungus', category: 'Restoratives', color: ItemColor.red, rarity: Rarity.common, rank: 1, description: 'Resting: Restore +1 Magic Peg'),
  CatalogItem(id: 'rst_sunblessed_weed', name: 'Sunblessed Weed', category: 'Restoratives', color: ItemColor.red, rarity: Rarity.uncommon, rank: 1, description: 'Restore 1 Health Peg'),
  CatalogItem(id: 'rst_djinnbane', name: 'Djinnbane', category: 'Restoratives', color: ItemColor.red, rarity: Rarity.uncommon, rank: 1, description: 'Restore 2 Actions'),
  CatalogItem(id: 'rst_minerals', name: 'Minerals', category: 'Restoratives', color: ItemColor.red, rarity: Rarity.common, rank: 1, description: 'Resting: Restore +1 Skill Peg'),
  CatalogItem(id: 'rst_powered_drakon_bone', name: 'Powered Drakon Bone', category: 'Restoratives', color: ItemColor.red, rarity: Rarity.uncommon, rank: 2, description: 'Restore 2 Actions'),

  // ─── Potions ───────────────────────────────────────────────────────────────
  CatalogItem(id: 'pot_magic_restore', name: 'Potion of Magic Restore', category: 'Potions', color: ItemColor.grey, rarity: Rarity.rare, rank: 1, description: 'Restore 4 Magic pegs'),
  CatalogItem(id: 'pot_action_restore', name: 'Potion of Action Restore', category: 'Potions', color: ItemColor.grey, rarity: Rarity.rare, rank: 1, description: 'Restore 3 Actions'),
  CatalogItem(id: 'pot_lesser_health', name: 'Potion of Lesser Health', category: 'Potions', color: ItemColor.grey, rarity: Rarity.rare, rank: 2, description: 'Restore 2 Health pegs'),
  CatalogItem(id: 'pot_skill_restore', name: 'Potion of Skill Restore', category: 'Potions', color: ItemColor.grey, rarity: Rarity.rare, rank: 2, description: 'Restore 3 Skill pegs'),
  CatalogItem(id: 'pot_potentium', name: 'Potentium', category: 'Potions', color: ItemColor.grey, rarity: Rarity.rare, rank: 2, description: 'See Forbidden Creed rulebook'),
  CatalogItem(id: 'pot_actions', name: 'Potion of Actions', category: 'Potions', color: ItemColor.grey, rarity: Rarity.exclusive, rank: 0, description: 'Restore 3 Actions'),
  CatalogItem(id: 'pot_magic', name: 'Potion of Magic', category: 'Potions', color: ItemColor.grey, rarity: Rarity.exclusive, rank: 0, description: 'Restore 4 Magic Pegs'),
  CatalogItem(id: 'pot_mighty_brew', name: 'Mighty Brew', category: 'Potions', color: ItemColor.grey, rarity: Rarity.exclusive, rank: 0, description: 'Gain +2 Combat dice until end of turn'),
  CatalogItem(id: 'pot_health', name: 'Potion of Health', category: 'Potions', color: ItemColor.grey, rarity: Rarity.exclusive, rank: 0, description: 'Restore 3 Health Pegs'),
  CatalogItem(id: 'pot_wardweavers_nip', name: "Wardweaver's Nip", category: 'Potions', color: ItemColor.grey, rarity: Rarity.exclusive, rank: 0, description: 'Gain +2 Magical Armour'),
  CatalogItem(id: 'pot_finesse', name: 'Potion of Finesse', category: 'Potions', color: ItemColor.grey, rarity: Rarity.exclusive, rank: 0, description: 'Gain Vicious until end of turn'),
  CatalogItem(id: 'pot_skill', name: 'Potion of Skill', category: 'Potions', color: ItemColor.grey, rarity: Rarity.exclusive, rank: 0, description: 'Restore 2 Skill Pegs'),
  CatalogItem(id: 'pot_cordial_of_cognisanse', name: 'Cordial of Cognisanse', category: 'Potions', color: ItemColor.grey, rarity: Rarity.exclusive, rank: 0, description: 'Gain 3 exp until end of turn, keep 1'),
  CatalogItem(id: 'pot_destinys_tincture', name: "Destiny's Tincture", category: 'Potions', color: ItemColor.grey, rarity: Rarity.exclusive, rank: 0, description: 'Gain one time re-roll'),
  CatalogItem(id: 'pot_dreamers_draught', name: "Dreamer's Draught", category: 'Potions', color: ItemColor.grey, rarity: Rarity.exclusive, rank: 0, description: 'Restore 1 Skill Peg and 2 Health Pegs, remove 1 Poisoned/Wounded token, Hazardous (Terrifying/Poisoned)'),
  CatalogItem(id: 'pot_admantine_elixir', name: 'Admantine Elixir', category: 'Potions', color: ItemColor.grey, rarity: Rarity.exclusive, rank: 0, description: 'Gain +2 Physical Armour, Immunity to Everything until end of turn'),
];
